on:
  push:
    branches:
      - main

jobs:
  release-v1_0:
    name: (Update) release v1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name $(git log -1 --pretty=format:'%an')
      - run: git config --global user.email $(git log -1 --pretty=format:'%ae')
      - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - run: scripts/build-tag.sh v1.0
