on:
  push:
    branches:
      - main

jobs:
  release-v1_0:
    name: (Update) release v1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: scripts/build-tag.sh v1.0
