on:
  push:
    branches:
      - main

jobs:
  release-v1_0:
    name: (Update) release v1.0
    runs-on: ubuntu-latest
    steps:
      - name: Build, commit & push new version
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          scripts/build-tag.sh v1.0
